/* ============================================
   Al Hilal International Clinic – Main JS
   ============================================ */

document.addEventListener('DOMContentLoaded', () => {

  AOS.init({ duration: 800, offset: 60, once: true, disable: 'mobile' });

  // Navbar scroll
  const navbar = document.getElementById('navbar');
  window.addEventListener('scroll', () => navbar.classList.toggle('scrolled', window.scrollY > 60));

  // Mobile nav toggle
  const navToggle = document.getElementById('navToggle');
  const navMenu = document.getElementById('navMenu');
  if (navToggle && navMenu) {
    navToggle.addEventListener('click', () => {
      navToggle.classList.toggle('active');
      navMenu.classList.toggle('active');
    });
    navMenu.querySelectorAll('a').forEach(link => {
      link.addEventListener('click', () => {
        navToggle.classList.remove('active');
        navMenu.classList.remove('active');
        document.querySelectorAll('.mega-menu').forEach(m => m.classList.remove('active'));
      });
    });
  }

  // Mega Menus
  document.querySelectorAll('.menu-trigger').forEach(trigger => {
    const mega = trigger.querySelector('.mega-menu');
    if (!mega) return;
    const link = trigger.querySelector('a');
    if (link) {
      link.addEventListener('click', (e) => {
        e.preventDefault();
        mega.classList.toggle('active');
      });
    }
    // Panel switching
    const leftBtns = mega.querySelectorAll('.mega-menu-left button');
    const panels = mega.querySelectorAll('.mega-panel');
    leftBtns.forEach(btn => {
      btn.addEventListener('click', () => {
        leftBtns.forEach(b => b.classList.remove('active'));
        btn.classList.add('active');
        panels.forEach(p => p.classList.remove('active'));
        const panel = mega.querySelector(`.mega-panel[data-panel="${btn.dataset.panel}"]`);
        if (panel) panel.classList.add('active');
      });
    });
  });
  document.addEventListener('click', (e) => {
    if (!e.target.closest('.menu-trigger')) {
      document.querySelectorAll('.mega-menu').forEach(m => m.classList.remove('active'));
    }
  });

  // Swipers
  if (document.querySelector('.specialists-swiper')) {
    new Swiper('.specialists-swiper', {
      slidesPerView: 1, spaceBetween: 24, loop: true,
      autoplay: { delay: 4000, disableOnInteraction: false },
      pagination: { el: '.swiper-pagination', clickable: true },
      navigation: { nextEl: '.swiper-button-next', prevEl: '.swiper-button-prev' },
      breakpoints: { 768: { slidesPerView: 2 }, 1024: { slidesPerView: 3 } }
    });
  }
  if (document.querySelector('.testimonials-swiper')) {
    new Swiper('.testimonials-swiper', {
      slidesPerView: 1, spaceBetween: 24, loop: true,
      autoplay: { delay: 5000, disableOnInteraction: false },
      pagination: { el: '.swiper-pagination', clickable: true }
    });
  }

  // Treatment filters
  document.querySelectorAll('.treatments-filter').forEach(filter => {
    const btns = filter.querySelectorAll('.filter-btn');
    const cards = filter.closest('.treatments')?.querySelectorAll('.treatment-card') || [];
    btns.forEach(btn => {
      btn.addEventListener('click', () => {
        btns.forEach(b => b.classList.remove('active'));
        btn.classList.add('active');
        const f = btn.dataset.filter;
        cards.forEach(card => {
          if (f === 'all' || card.dataset.category === f) {
            card.style.display = 'block';
            card.style.animation = 'fadeIn 0.4s ease';
          } else {
            card.style.display = 'none';
          }
        });
      });
    });
  });

  // Gallery filters
  document.querySelectorAll('.gallery-filter').forEach(filter => {
    const btns = filter.querySelectorAll('.filter-btn');
    const items = filter.closest('.gallery')?.querySelectorAll('.gallery-item') || [];
    btns.forEach(btn => {
      btn.addEventListener('click', () => {
        btns.forEach(b => b.classList.remove('active'));
        btn.classList.add('active');
        const f = btn.dataset.filter;
        items.forEach(item => {
          if (f === 'all' || item.dataset.category === f) {
            item.style.display = 'block';
            item.style.animation = 'fadeIn 0.4s ease';
          } else {
            item.style.display = 'none';
          }
        });
      });
    });
  });

  // Counter animation
  const counters = document.querySelectorAll('.stat-num');
  const counterObserver = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        const el = entry.target;
        const target = parseInt(el.dataset.count);
        if (!target) return;
        let current = 0;
        const increment = Math.ceil(target / 50);
        const timer = setInterval(() => {
          current += increment;
          if (current >= target) { el.textContent = target; clearInterval(timer); }
          else { el.textContent = current; }
        }, 40);
        counterObserver.unobserve(el);
      }
    });
  }, { threshold: 0.5 });
  counters.forEach(c => counterObserver.observe(c));

  // ========== ARABIC TRANSLATIONS ==========
  let currentLang = 'en';

  const enText = {
    'top.location': 'Salmiya, Kuwait',
    'top.hours': 'Sat–Thu: 10:00 AM – 8:00 PM',
    'top.whatsapp': 'WhatsApp',
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.treatments': 'Treatments',
    'nav.specialists': 'Specialists',
    'nav.gallery': 'Gallery',
    'nav.testimonials': 'Testimonials',
    'nav.contact': 'Contact',
    'nav.book': 'Book Now',
    'menu.faceSkin': 'Face & Skin',
    'menu.radiantSkin': 'Radiant Skin',
    'menu.bodyContouring': 'Body Contouring',
    'menu.laserHair': 'Laser Hair Removal',
    'hero.badge': 'Salmiya, Kuwait',
    'hero.sub': 'Advanced dermatology, aesthetic medicine & laser treatments in the heart of Salmiya.<br>Your journey to radiant, healthy skin begins here.',
    'hero.cta1': 'Book Appointment',
    'hero.whatsapp': 'WhatsApp Us',
    'about.tag': 'Welcome to',
    'about.title': 'Al Hilal International Clinic',
    'about.desc': 'Your trusted destination for premium dermatology and aesthetic medicine in Salmiya, Kuwait. We combine medical excellence with a luxury patient experience.',
    'about.exp': 'Years of Excellence',
    'about.p1': 'At Al Hilal International Clinic, we are dedicated to providing world-class aesthetic and dermatological care tailored to the unique needs of our patients in Kuwait. Our clinic is led by a team of highly qualified specialists with extensive experience in medical and cosmetic dermatology.',
    'about.p2': 'From advanced laser treatments to injectable aesthetics and medical dermatology, every procedure is performed with precision, using the latest technology and highest safety standards. We believe in natural-looking results that enhance your confidence and well-being.',
    'about.stat1': 'Happy Patients',
    'about.stat2': 'Years Experience',
    'about.stat3': 'Treatments',
    'why.tag': 'Why Choose Us',
    'why.title': 'The Al Hilal Difference',
    'why.card1.title': 'Expert Leadership',
    'why.card1.text': 'Led by board-certified dermatologists with extensive international experience in aesthetic medicine.',
    'why.card2.title': 'Cutting-Edge Technology',
    'why.card2.text': 'The latest dermatological and laser innovations for safe, effective, and reliable procedures.',
    'why.card3.title': 'Personalized Care',
    'why.card3.text': 'Custom treatment plans designed for your unique skin type, concerns, and aesthetic goals.',
    'why.card4.title': 'Proven Results',
    'why.card4.text': 'Trusted by thousands of satisfied patients for outstanding, natural-looking outcomes.',
    'why.card5.title': 'Luxury Experience',
    'why.card5.text': 'Premium comfort and privacy in a sophisticated, welcoming environment.',
    'why.card6.title': 'Prime Location',
    'why.card6.text': 'Conveniently located in Salmiya, easily accessible from all areas of Kuwait.',
    'services.tag': 'Our Expertise',
    'services.title': 'Comprehensive Aesthetic & Dermatology Services',
    'services.desc': 'From injectables to laser, we offer a full spectrum of advanced treatments tailored to your needs.',
    'services.cat1': 'Injectable Aesthetics',
    'services.cat1.desc': 'Botox, dermal fillers, skin boosters & advanced injectable treatments for natural rejuvenation.',
    'services.cat2': 'Laser Treatments',
    'services.cat2.desc': 'Advanced laser hair removal, skin rejuvenation, pigmentation correction & skin tightening.',
    'services.cat3': 'Medical Dermatology',
    'services.cat3.desc': 'Expert diagnosis & treatment for acne, eczema, psoriasis, skin infections & all dermatological conditions.',
    'services.cat4': 'Skin Rejuvenation',
    'services.cat4.desc': 'Chemical peels, microneedling, HydraFacial, PRP & advanced skin revitalization therapies.',
    'services.view': 'View Details',
    'services.pageTitle': 'Our Comprehensive Services',
    'services.pageDesc': 'From advanced injectables to medical dermatology, every treatment is tailored to your unique needs.',
    'treatments.tag': 'Treatments',
    'treatments.title': 'Explore Our Full Range of Treatments',
    'treatments.desc': 'Every treatment is performed by our expert team using the latest medical technology.',
    'treatments.allBtn': 'View All Treatments',
    'filter.all': 'All',
    'filter.injectables': 'Injectables',
    'filter.laser': 'Laser',
    'filter.skin': 'Skin Care',
    'filter.body': 'Body',
    'filter.botox': 'Botox',
    'filter.fillers': 'Fillers',
    'gallery.tag': 'Results',
    'gallery.title': 'Before & After',
    'gallery.desc': 'Real results from our patients. Each transformation reflects our commitment to excellence.',
    'gallery.botox': 'Forehead Botox',
    'gallery.fillers': 'Lip Fillers',
    'gallery.laser': 'Laser Hair Removal',
    'gallery.skin': 'Acne Treatment',
    'gallery.jawline': 'Jawline Definition',
    'gallery.neck': 'Neck Botox',
    'gallery.pigmentation': 'Pigmentation Correction',
    'gallery.rejuvenation': 'Skin Rejuvenation',
    'testimonials.tag': 'Testimonials',
    'testimonials.title': 'What Our Patients Say',
    'testimonial.1': '"Exceptional care from the moment I walked in. Dr. Al-Rashid took the time to understand my concerns and the results exceeded my expectations. Truly a world-class clinic."',
    'testimonial.1t': 'Botox Treatment',
    'testimonial.2': '"I\'ve been coming to Al Hilal for over a year for laser hair removal and the results are amazing. The team is professional, friendly, and makes you feel completely comfortable."',
    'testimonial.2t': 'Laser Hair Removal',
    'testimonial.3': '"The chemical peel treatment transformed my skin. I\'ve never felt more confident. Thank you to the entire team at Al Hilal for your expertise and care."',
    'testimonial.3t': 'Chemical Peel',
    'testimonial.4': '"Professional, clean, and results-driven. My filler treatment looks completely natural — exactly what I wanted. Highly recommend Al Hilal Clinic."',
    'testimonial.4t': 'Dermal Fillers',
    'testimonial.5': '"Best dermatology clinic in Kuwait. Dr. Fatima helped me manage my eczema when no one else could. Finally, I have my skin back. Forever grateful."',
    'testimonial.5t': 'Medical Dermatology',
    'contact.tag': 'Get In Touch',
    'contact.title': 'Book Your Appointment',
    'contact.desc': 'Ready to start your journey? Contact us or fill in the form and we\'ll get back to you promptly.',
    'contact.call': 'Call Us',
    'contact.whatsapp': 'WhatsApp',
    'contact.location': 'Location',
    'contact.location.text': 'Salmiya, Kuwait',
    'contact.hours': 'Working Hours',
    'contact.hours.text': 'Saturday – Thursday: 10:00 AM – 8:00 PM<br>Friday: Closed',
    'contact.hours.short': 'Sat–Thu: 10 AM – 8 PM',
    'form.name': 'Full Name *',
    'form.phone': 'Phone Number *',
    'form.email': 'Email',
    'form.service': 'Service Interested In *',
    'form.select': 'Select a service',
    'form.message': 'Message *',
    'form.submit': 'Send Message',
    'footer.desc': 'Al Hilal International Clinic is a premier dermatology and aesthetic medicine center in Salmiya, Kuwait, offering advanced, safe, and personalized skin and cosmetic treatments.',
    'footer.quick': 'Quick Links',
    'footer.treatments': 'Treatments',
    'footer.contact': 'Contact',
    'footer.rights': 'All Rights Reserved.',
    'specialists.tag': 'Our Team',
    'specialists.title': 'Meet Our Expert Specialists',
    'specialists.desc': 'Highly qualified professionals dedicated to your skin health and aesthetic goals.',
    'specialists.role1': 'Medical Director & Consultant Dermatologist',
    'specialists.role2': 'Aesthetic Medicine Specialist',
    'specialists.role3': 'Senior Dermatologist',
    'specialists.role4': 'Laser & Aesthetics Specialist',
    'specialists.bio1': 'Board-certified dermatologist with over 15 years of experience in medical and aesthetic dermatology, recognized internationally for excellence in patient care.',
    'specialists.bio2': 'Expert in injectable treatments, laser therapy, and advanced aesthetic procedures with 10+ years experience and international training.',
    'specialists.bio3': 'Specializing in medical dermatology, skin cancer screening, and management of chronic skin conditions with a patient-centered approach.',
    'specialists.bio4': 'Expert in laser treatments, skin rejuvenation, and body contouring with advanced international training and certification.',
    'specialists.cred1': 'Arab Board of Dermatology',
    'specialists.cred1b': 'Fellow, American Academy of Dermatology',
    'specialists.cred2': 'American Board of Aesthetic Medicine',
    'specialists.cred2b': 'Certified Laser Specialist',
    'specialists.cred3': 'Kuwait Medical Board',
    'specialists.cred3b': 'European Academy of Dermatology',
    'specialists.cred4': 'International Laser Institute',
    'specialists.cred4b': 'Certified Aesthetic Practitioner',
    // Treatments i18n
    'treat.botox': 'Botox & Dysport',
    'treat.botox.desc': 'Expert wrinkle reduction with Botox and Dysport. Smooth fine lines, crow feet, forehead wrinkles, and frown lines for a refreshed, natural look.',
    'treat.masseter': 'Masseter Botox',
    'treat.skinBooster': 'High Potency Skin Booster',
    'treat.nefertiti': 'Nefertiti Lift (Neck & Jawline)',
    'treat.hyperhidrosis': 'Hyperhidrosis',
    'treat.eyelid': 'Eyelid Lifting',
    'treat.neckTight': 'Neck Tightening',
    'treat.cheeks': 'Cheeks, Chin, Lips, Temples',
    'treat.nasolabial': 'Nasolabial Folds',
    'treat.radiesse': 'Radiesse',
    'treat.nose': 'Non-Surgical Nose Reshaping',
    'treat.profhilo': 'Profhilo',
    'treat.polynucleotides': 'Polynucleotides',
    'treat.sculptra': 'Sculptra',
    'treat.prpMicro': 'PRP & Exosome Microneedling',
    'treat.prpMicro.desc': 'Platelet-Rich Plasma therapy and advanced microneedling for natural collagen stimulation and rejuvenation.',
    'treat.rfMicro': 'Radiofrequency Microneedling',
    'treat.doubleChin': 'Double Chin',
    'treat.meso': 'Mesotherapy for Fat & Tone',
    'treat.jawline': 'Jawline Definition',
    'treat.fillerDissolve': 'Filler Dissolving',
    'treat.corrective': 'Corrective Treatments',
    'treat.skinTags': 'Skin Tags & Moles',
    'treat.prpConc': 'PRP Concentrate',
    'treat.hairLab': 'Lab Diagnostics for Hair Loss',
    'treat.exosomalDermapen': 'Exosomal Dermapen',
    'treat.medicalMeso': 'Medical Mesotherapy',
    'treat.alopecia': 'Alopecia Areata',
    'treat.fillers': 'Dermal Fillers',
    'treat.fillers.desc': 'Restore volume, enhance contours, and rejuvenate your appearance with premium dermal fillers.',
    'treat.laserHair': 'Laser Hair Removal',
    'treat.laserHair.desc': 'Permanent hair reduction using advanced laser technology. Safe, effective, suitable for all skin types.',
    'treat.chemicalPeels': 'Chemical Peels & Facials',
    'treat.chemicalPeels.desc': 'Professional-grade chemical peels and advanced facial treatments for radiant, healthy skin.',
    'treat.dermapen': 'Dermapen / Microneedling',
    'treat.hydracool': 'HydraCool',
    'treat.nanofacial': 'NanoFacial',
    'treat.vivace': 'Vivace Microneedling',
    'treat.hydrafacial': 'Microdermabrasion/HydraFacial',
    'treat.exosome': 'Exosome',
    'treat.salmonDna': 'Salmon DNA',
    'treat.carboxy': 'Carboxy Therapy',
    'treat.fatDissolving': 'Fat-Dissolving Injections',
    'treat.btlExilis': 'BTL Exilis Ultra',
    'treat.collagenStim': 'Collagen Stimulators',
    'treat.bodyContour': 'Body Contouring',
    'treat.bodyContour.desc': 'Non-invasive body contouring and fat reduction for a more sculpted physique.',
    'treat.skinRejuv': 'Skin Rejuvenation',
    // Services page
    'serv.injectables': 'Injectable Aesthetics',
    'serv.injectables.desc': 'Premium injectable treatments including Botox, dermal fillers, skin boosters, and biostimulators for natural, rejuvenated results.',
    'serv.laser': 'Laser Treatments',
    'serv.laser.desc': 'State-of-the-art laser technology for hair removal, skin rejuvenation, pigmentation correction, and skin tightening.',
    'serv.laser.rejuv': 'Laser Skin Rejuvenation',
    'serv.laser.pigment': 'Pigmentation Correction',
    'serv.laser.tighten': 'Skin Tightening',
    'serv.laser.vascular': 'Vascular Lesion Treatment',
    'serv.dermatology': 'Medical Dermatology',
    'serv.dermatology.desc': 'Expert diagnosis and treatment of all dermatological conditions by our board-certified specialists.',
    'serv.derm.acne': 'Acne & Acne Scar Treatment',
    'serv.derm.eczema': 'Eczema & Psoriasis',
    'serv.derm.infection': 'Skin Infections',
    'serv.derm.screening': 'Skin Cancer Screening',
    'serv.derm.allergy': 'Allergic Skin Conditions',
    'serv.skinRejuv': 'Skin Rejuvenation',
    'serv.skinRejuv.desc': 'Advanced treatments to revitalize and restore your skin\'s natural radiance and youthful appearance.',
    'serv.skinRejuv.antiAge': 'Anti-Aging Solutions',
    'serv.skinRejuv.prp': 'PRP Facial',
    'serv.bodyContour': 'Body Contouring',
    'serv.bodyContour.desc': 'Non-invasive body contouring and fat reduction for a more sculpted, confident you.',
    'serv.consultation': 'General Consultations',
    'serv.consultation.desc': 'Comprehensive consultations with our expert dermatologists to assess your needs and create a personalized treatment plan.',
    'serv.consult.skin': 'Full Skin Analysis',
    'serv.consult.hair': 'Hair & Scalp Assessment',
    'serv.consult.aesthetic': 'Aesthetic Consultation',
    'serv.consult.custom': 'Custom Treatment Plan',
    // Page & breadcrumb keys
    'breadcrumb.home': 'Home',
    'breadcrumb.treatments': 'Treatments',
    'breadcrumb.faceSkin': 'Face &amp; Skin',
    'breadcrumb.radiantSkin': 'Radiant Skin',
    'breadcrumb.bodyContour': 'Body Contouring',
    'breadcrumb.laserHair': 'Laser Hair Removal',
    'faceSkin.pageTitle': 'Face &amp; Skin Treatments',
    'faceSkin.pageDesc': 'Advanced injectables, skin rejuvenation and facial aesthetic treatments tailored to enhance your natural beauty at Al Hilal International Clinic.',
    'faceSkin.tag': 'Our Expertise',
    'faceSkin.sectionTitle': 'Comprehensive Face &amp; Skin Treatments',
    'faceSkin.sectionDesc': 'Every treatment is performed by our expert medical team using premium products and the latest techniques for natural, lasting results.',
    'faceSkin.bookingText': 'Not sure which treatment is right for you? Book a consultation with our specialists today.',
    'faceSkin.bookingWA': 'Book via WhatsApp',
    'faceSkin.bookingForm': 'Book Appointment',
    'radiant.pageTitle': 'Radiant Skin Treatments',
    'radiant.pageDesc': 'Advanced skin rejuvenation treatments designed to restore your skin\'s natural glow, texture, and vitality.',
    'bodyContouring.pageTitle': 'Body Contouring',
    'bodyContouring.pageDesc': 'Non-invasive body sculpting and fat reduction treatments for a more contoured, confident you.',
    'laserHair.pageTitle': 'Laser Hair Removal',
    'laserHair.pageDesc': 'Safe, effective permanent hair reduction using advanced laser technology. Suitable for all skin types.',
    'td.enquire': 'Enquire on WhatsApp',
    'td.book': 'Book Consultation',
    // Face & Skin treatment descs & list items
    'treat.masseter.desc': 'Masseter Botox involves targeted injections into the masseter muscles of the jaw to slim the lower face and relieve teeth grinding (bruxism). This popular treatment softens a square jawline, creating a more V-shaped, feminine or balanced facial contour. It also alleviates tension headaches, jaw clenching and TMJ discomfort. The effects develop over 2–4 weeks and typically last 4–6 months.',
    'treat.masseter.li1': 'Jaw slimming &amp; V-shape contouring',
    'treat.masseter.li2': 'Teeth grinding (bruxism) relief',
    'treat.masseter.li3': 'TMJ pain &amp; tension headaches',
    'treat.masseter.li4': 'Facial asymmetry correction',
    'treat.masseter.li5': 'Non-surgical face slimming',
    'treat.skinBooster.desc': 'High Potency Skin Boosters are advanced injectable treatments that deliver a powerful blend of hyaluronic acid, amino acids, vitamins and antioxidants deep into the dermis. Unlike superficial moisturisers, these boosters hydrate the skin from within, stimulating collagen production and improving elasticity. The result is a radiant, plump, dewy complexion with reduced fine lines and improved skin texture. A course of 2–3 sessions is recommended for optimal, long-lasting results.',
    'treat.skinBooster.li1': 'Deep hydration &amp; skin plumping',
    'treat.skinBooster.li2': 'Collagen &amp; elastin stimulation',
    'treat.skinBooster.li3': 'Fine line &amp; wrinkle reduction',
    'treat.skinBooster.li4': 'Improved skin texture &amp; radiance',
    'treat.skinBooster.li5': 'Dull, tired &amp; dehydrated skin',
    'treat.nefertiti.desc': 'The Nefertiti Lift is a non-surgical neck and jawline rejuvenation technique using strategic Botox injections. By relaxing the platysma bands (the vertical neck muscles) and the depressor muscles pulling down the jaw, the treatment creates a visible lift and tightening effect. It defines the jawline, reduces neck banding and softens marionette lines, giving a more sculpted profile. The procedure takes under 20 minutes with no downtime and results last 3–4 months.',
    'treat.nefertiti.li1': 'Platysma band reduction',
    'treat.nefertiti.li2': 'Jawline definition &amp; lift',
    'treat.nefertiti.li3': 'Neck tightening &amp; contouring',
    'treat.nefertiti.li4': 'Marionette line softening',
    'treat.nefertiti.li5': 'Non-surgical lower face lift',
    'treat.hyperhidrosis.desc': 'Hyperhidrosis (excessive sweating) can be effectively treated with Botox injections in the underarms, palms, soles or forehead. Botox blocks the chemical signals that stimulate sweat glands, significantly reducing perspiration in the treated area. The treatment is quick, minimally invasive and provides relief for 6–12 months. Many patients report a life-changing improvement in comfort and confidence after just one session.',
    'treat.hyperhidrosis.li1': 'Excessive underarm sweating',
    'treat.hyperhidrosis.li2': 'Palmar hyperhidrosis (sweaty palms)',
    'treat.hyperhidrosis.li3': 'Plantar hyperhidrosis (sweaty feet)',
    'treat.hyperhidrosis.li4': 'Facial blushing &amp; sweating',
    'treat.hyperhidrosis.li5': 'Long-lasting sweat reduction (6–12 months)',
    'treat.eyelid.desc': 'Non-surgical eyelid lifting uses targeted Botox injections around the brow and eye area to open up the eyes and create a more alert, youthful appearance. By relaxing the muscles that pull the brows down and the orbicularis oculi, the eyebrows lift subtly and crow\'s feet are smoothed. The treatment can also address drooping upper eyelids and asymmetry. Results are visible within a week and last 3–4 months with zero downtime.',
    'treat.eyelid.li1': 'Drooping upper eyelids',
    'treat.eyelid.li2': 'Brow ptosis (low brows)',
    'treat.eyelid.li3': 'Periorbital fine lines &amp; crow\'s feet',
    'treat.eyelid.li4': 'Asymmetric eye appearance',
    'treat.eyelid.li5': 'Tired, heavy-looking eyes',
    'treat.neckTight.desc': 'Neck tightening treatments combine laser, radiofrequency or injectable therapies to firm and rejuvenate loose, sagging skin on the neck and d\u00e9colletage. These non-invasive modalities stimulate collagen and elastin remodelling, improving skin laxity and reducing the appearance of horizontal neck lines (tech neck). Patients enjoy a smoother, more contoured neck profile without surgery or extended recovery. A series of sessions is typically recommended for best outcomes.',
    'treat.neckTight.li1': 'Loose, sagging neck skin',
    'treat.neckTight.li2': 'Horizontal neck lines (tech neck)',
    'treat.neckTight.li3': 'Loss of jawline definition',
    'treat.neckTight.li4': 'Turkey neck / double chin',
    'treat.neckTight.li5': 'Non-invasive skin tightening',
    'treat.cheeks.desc': 'Premium dermal fillers restore lost volume, enhance facial contours and rejuvenate the face at any age. Using hyaluronic acid-based fillers, our specialists can augment cheekbones, define the chin, plump the lips and restore volume to hollow temples. The treatment is customised to your facial anatomy and aesthetic goals, delivering natural-looking enhancement with immediate results. Effects typically last 9–18 months depending on the product used and area treated.',
    'treat.cheeks.li1': 'Sunken cheeks &amp; midface volume loss',
    'treat.cheeks.li2': 'Lip enhancement &amp; definition',
    'treat.cheeks.li3': 'Chin augmentation &amp; projection',
    'treat.cheeks.li4': 'Temple hollowing',
    'treat.cheeks.li5': 'Facial asymmetry correction',
    'treat.nasolabial.desc': 'Nasolabial folds (the lines running from the nose to the corners of the mouth) deepen with age as facial fat pads descend and collagen is lost. Dermal filler injections safely soften these folds by restoring volume and support to the midface. The result is a smoother, more rested appearance without looking overfilled. Our practitioners use gentle techniques and premium fillers to achieve beautiful, lasting correction.',
    'treat.nasolabial.li1': 'Deep nasolabial folds (smile lines)',
    'treat.nasolabial.li2': 'Midface volume loss',
    'treat.nasolabial.li3': 'Marionette lines',
    'treat.nasolabial.li4': 'Tired or gaunt facial appearance',
    'treat.nasolabial.li5': 'Non-surgical midface rejuvenation',
    'treat.radiesse.desc': 'Radiesse is a unique biostimulatory filler made of calcium hydroxylapatite microspheres suspended in a gel carrier. It provides immediate volume correction while stimulating your own collagen production for continued improvement over time. Radiesse is particularly effective for deeper wrinkles, cheek augmentation, jawline contouring and hand rejuvenation. Results last 12–18 months or longer, making it a cost-effective choice for long-term facial rejuvenation.',
    'treat.radiesse.li1': 'Deep nasolabial folds &amp; marionette lines',
    'treat.radiesse.li2': 'Cheek volume &amp; lift',
    'treat.radiesse.li3': 'Jawline &amp; chin contouring',
    'treat.radiesse.li4': 'Hand rejuvenation',
    'treat.radiesse.li5': 'Natural collagen stimulation',
    'treat.nose.desc': 'Non-surgical rhinoplasty uses dermal fillers to reshape and refine the nose without surgery or downtime. Fillers can smooth a dorsal hump, lift the nasal tip, correct asymmetry and improve nasal profile. The procedure is performed in under 30 minutes using topical anaesthesia for comfort. Results are immediate and reversible, lasting 12–18 months, making it an ideal option for those exploring nasal aesthetics.',
    'treat.nose.li1': 'Dorsal hump camouflage',
    'treat.nose.li2': 'Nasal tip lift &amp; refinement',
    'treat.nose.li3': 'Nasal asymmetry correction',
    'treat.nose.li4': 'Bridge augmentation',
    'treat.nose.li5': 'Non-surgical profile balancing',
    'treat.profhilo.desc': 'Profhilo is a revolutionary injectable treatment that combines high-concentration hyaluronic acid with a unique dispersing technology for deep tissue hydration and collagen remodelling. Unlike traditional fillers, Profhilo spreads evenly through the tissue to improve skin laxity, firmness and overall quality. It is especially popular for treating ageing hands, the face, neck and d\u00e9colletage. Two sessions spaced one month apart deliver outstanding, long-lasting results.',
    'treat.profhilo.li1': 'Skin laxity &amp; sagging',
    'treat.profhilo.li2': 'Dehydrated, dull skin',
    'treat.profhilo.li3': 'Fine lines &amp; crepey texture',
    'treat.profhilo.li4': 'Hand rejuvenation',
    'treat.profhilo.li5': 'Overall skin quality improvement',
    'treat.polynucleotides.desc': 'Polynucleotide treatments harness the power of purified DNA fragments to stimulate cellular regeneration and tissue repair. These bio-revitalising injections deeply nourish the skin, promoting collagen synthesis, improving hydration and reducing inflammation. Polynucleotides are excellent for treating fine lines, dark circles, acne scars and overall skin ageing. A course of 3 sessions yields progressive improvements in skin tone, texture and firmness.',
    'treat.polynucleotides.li1': 'Fine lines &amp; skin ageing',
    'treat.polynucleotides.li2': 'Under-eye dark circles &amp; hollows',
    'treat.polynucleotides.li3': 'Acne scars &amp; textural issues',
    'treat.polynucleotides.li4': 'Dehydrated, damaged skin',
    'treat.polynucleotides.li5': 'Skin regeneration &amp; repair',
    'treat.sculptra.desc': 'Sculptra is a unique biostimulatory injectable made from poly-L-lactic acid that gradually restores facial volume by stimulating your own collagen production. Over a course of 2–3 sessions, Sculptra rebuilds the facial structure from within, correcting deep volume loss in the cheeks, temples, and jawline for a natural, progressive rejuvenation. Results develop over several months and can last more than two years. It is ideal for patients wanting subtle, long-lasting anti-ageing without obvious change.',
    'treat.sculptra.li1': 'Age-related facial volume loss',
    'treat.sculptra.li2': 'Sunken cheeks &amp; temples',
    'treat.sculptra.li3': 'Nasolabial folds &amp; marionette lines',
    'treat.sculptra.li4': 'Jawline &amp; chin recontouring',
    'treat.sculptra.li5': 'Gradual, natural collagen renewal',
    'treat.prpMicro.li1': 'Acne scars &amp; enlarged pores',
    'treat.prpMicro.li2': 'Fine lines &amp; wrinkles',
    'treat.prpMicro.li3': 'Dull, uneven skin tone',
    'treat.prpMicro.li4': 'Stretch marks &amp; scars',
    'treat.prpMicro.li5': 'Overall skin rejuvenation &amp; collagen induction',
    'treat.rfMicro.desc': 'Radiofrequency (RF) microneedling combines the collagen-induction power of microneedling with the skin-tightening energy of radiofrequency. Ultra-fine needles penetrate the dermis and deliver controlled RF heat, stimulating deep collagen remodelling while protecting the skin\'s surface. This technology is highly effective for skin tightening, scar revision, pore refinement and laxity correction. Most patients see noticeable improvement after a single session, with optimal results after 2–3 treatments.',
    'treat.rfMicro.li1': 'Skin laxity &amp; sagging',
    'treat.rfMicro.li2': 'Acne scars &amp; boxcar scars',
    'treat.rfMicro.li3': 'Enlarged pores &amp; textural issues',
    'treat.rfMicro.li4': 'Fine lines &amp; jowls',
    'treat.rfMicro.li5': 'Non-surgical face &amp; neck tightening',
    'treat.doubleChin.desc': 'Submental fat (double chin) can be effectively reduced using non-surgical treatments such as deoxycholic acid injections or laser lipolysis. These targeted therapies break down fat cells under the chin, which are then naturally eliminated by the body. The treatment contours the jawline and profile, creating a more defined and youthful appearance. A series of 2–4 sessions is typically required, with results becoming visible within weeks.',
    'treat.doubleChin.li1': 'Submental fat (double chin)',
    'treat.doubleChin.li2': 'Poor jawline definition',
    'treat.doubleChin.li3': 'Fullness under the chin',
    'treat.doubleChin.li4': 'Non-surgical chin contouring',
    'treat.doubleChin.li5': 'Permanent fat reduction',
    'treat.meso.desc': 'Mesotherapy involves micro-injections of a custom blend of vitamins, enzymes, amino acids and lipolytic compounds directly into the mesoderm (middle layer of skin). This treatment targets localised fat deposits, cellulite and skin laxity while simultaneously nourishing and toning the treated area. Commonly treated areas include the face, abdomen, thighs and arms. A course of 4–6 weekly sessions delivers progressive fat reduction and improved skin firmness.',
    'treat.meso.li1': 'Localised fat deposits',
    'treat.meso.li2': 'Cellulite reduction',
    'treat.meso.li3': 'Skin laxity &amp; poor tone',
    'treat.meso.li4': 'Facial slimming &amp; contouring',
    'treat.meso.li5': 'Body sculpting without surgery',
    'treat.jawline.desc': 'Jawline definition uses dermal fillers to sculpt and enhance the mandibular contour, creating a sharper, more aesthetically pleasing jawline. By adding structure to the jaw angle and chin, fillers can transform a weak or poorly defined jaw into a strong, balanced feature. This treatment is especially popular among both men and women seeking a more structured lower face. Results are immediate and can last 12–18 months with premium fillers.',
    'treat.jawline.li1': 'Weak or undefined jawline',
    'treat.jawline.li2': 'Lack of chin projection',
    'treat.jawline.li3': 'Jaw asymmetry',
    'treat.jawline.li4': 'Age-related jawline laxity',
    'treat.jawline.li5': 'Non-surgical facial masculinisation / feminisation',
    'treat.fillerDissolve.desc': 'Hyaluronidase injections safely and rapidly dissolve unwanted or overfilled hyaluronic acid fillers. Whether you have lumps, asymmetry, migration or simply changed your mind, filler dissolving provides immediate correction. The enzyme breaks down the filler, restoring your natural appearance within 24–48 hours. This treatment is also used to manage complications such as vascular occlusion, ensuring patient safety at all times.',
    'treat.fillerDissolve.li1': 'Overfilled or lumpy areas',
    'treat.fillerDissolve.li2': 'Filler asymmetry or migration',
    'treat.fillerDissolve.li3': 'Tyndall effect (blueish tint)',
    'treat.fillerDissolve.li4': 'Unsatisfactory filler results',
    'treat.fillerDissolve.li5': 'Vascular occlusion emergency treatment',
    'treat.corrective.desc': 'Our corrective treatments address a wide range of skin concerns including hyperpigmentation, melasma, post-inflammatory erythema, sun damage and uneven texture. Using a combination of medical-grade peels, lasers, topical therapies and advanced skincare, we create a personalised plan to restore your skin\'s health and clarity. Each protocol is tailored to your skin type and condition for safe, effective results. Ongoing support and follow-up ensure long-term improvement.',
    'treat.corrective.li1': 'Hyperpigmentation &amp; melasma',
    'treat.corrective.li2': 'Post-inflammatory erythema (redness)',
    'treat.corrective.li3': 'Sun spots &amp; photoageing',
    'treat.corrective.li4': 'Uneven skin tone &amp; texture',
    'treat.corrective.li5': 'Medical-grade corrective skincare plans',
    'treat.skinTags.desc': 'We offer safe, effective removal of skin tags, moles, warts, seborrheic keratoses and other benign skin lesions using laser, cryotherapy or surgical excision. All procedures are performed by our medical team with precision and minimal discomfort. Lesions are removed in a single session with virtually no downtime and excellent cosmetic outcomes. Every lesion is carefully assessed to ensure safety and appropriate treatment selection.',
    'treat.skinTags.li1': 'Skin tags (acrochordons)',
    'treat.skinTags.li2': 'Benign moles &amp; naevi',
    'treat.skinTags.li3': 'Seborrheic keratoses',
    'treat.skinTags.li4': 'Warts &amp; papillomas',
    'treat.skinTags.li5': 'Minimal scarring &amp; fast healing',
    'treat.prpConc.desc': 'PRP (Platelet-Rich Plasma) Concentrate therapy uses your own blood\'s growth factors to stimulate healing, collagen production and tissue regeneration. After a simple blood draw, the platelet-rich plasma is separated and injected into targeted areas of the face, scalp or body. PRP is highly effective for facial rejuvenation, hair restoration and scar improvement. The treatment is natural, safe and biocompatible with no risk of allergic reaction.',
    'treat.prpConc.li1': 'Facial rejuvenation (vampire facial)',
    'treat.prpConc.li2': 'Hair loss &amp; thinning',
    'treat.prpConc.li3': 'Acne scars &amp; wound healing',
    'treat.prpConc.li4': 'Under-eye dark circles &amp; hollows',
    'treat.prpConc.li5': 'Natural collagen induction',
    'treat.hairLab.desc': 'Comprehensive laboratory diagnostics identify the root causes of hair loss, enabling targeted, effective treatment. Our panel includes hormone profiling (DHT, oestrogen, thyroid), nutritional deficiency screening (iron, ferritin, vitamin D, zinc), and inflammatory markers. Results are interpreted by our specialists who create a personalised treatment plan addressing your specific hair loss type. This evidence-based approach ensures the best possible outcomes for hair restoration.',
    'treat.hairLab.li1': 'Androgenetic alopecia (pattern baldness)',
    'treat.hairLab.li2': 'Telogen effluvium (stress-related shedding)',
    'treat.hairLab.li3': 'Nutritional deficiency hair loss',
    'treat.hairLab.li4': 'Hormonal imbalance (thyroid, DHT)',
    'treat.hairLab.li5': 'Personalised treatment plans',
    'treat.exosomalDermapen.desc': 'Exosomal Dermapen combines medical-grade microneedling with topical application of exosome-rich serum for advanced skin regeneration. Exosomes are nano-sized vesicles packed with growth factors, cytokines and signalling proteins that communicate with skin cells to accelerate repair and rejuvenation. This synergistic treatment dramatically improves scar appearance, reduces pigmentation, tightens pores and restores skin radiance. A course of 3 sessions yields exceptional, cumulative results.',
    'treat.exosomalDermapen.li1': 'Acne scars &amp; surgical scars',
    'treat.exosomalDermapen.li2': 'Pigmentation &amp; sun damage',
    'treat.exosomalDermapen.li3': 'Enlarged pores &amp; textural irregularity',
    'treat.exosomalDermapen.li4': 'Fine lines &amp; skin laxity',
    'treat.exosomalDermapen.li5': 'Accelerated skin repair &amp; regeneration',
    'treat.medicalMeso.desc': 'Medical mesotherapy is a regulated, prescription-based injectable treatment that delivers active ingredients directly to the target tissue. Unlike cosmetic mesotherapy, our medical-grade formulations contain precisely dosed vitamins, minerals, amino acids and hyaluronic acid for therapeutic skin restoration. It is indicated for dehydrated, ageing, pigmented or compromised skin and is often used alongside other aesthetic procedures. Treatments are tailored to each patient\'s clinical needs.',
    'treat.medicalMeso.li1': 'Severely dehydrated skin',
    'treat.medicalMeso.li2': 'Ageing &amp; photoaged skin',
    'treat.medicalMeso.li3': 'Post-procedure skin recovery',
    'treat.medicalMeso.li4': 'Pigmentation &amp; dullness',
    'treat.medicalMeso.li5': 'Prescription-strength revitalisation',
    'treat.alopecia.desc': 'Alopecia areata is an autoimmune condition causing patchy hair loss that can affect the scalp, eyebrows, beard and body. Our clinic offers advanced treatment options including topical immunotherapy, corticosteroid injections, PRP therapy and JAK inhibitors to suppress the immune attack and promote hair regrowth. Each treatment plan is individualised based on the severity and pattern of hair loss. Early intervention offers the best prognosis for full recovery.',
    'treat.alopecia.li1': 'Patchy scalp hair loss',
    'treat.alopecia.li2': 'Eyebrow &amp; beard alopecia',
    'treat.alopecia.li3': 'Totalis &amp; universalis forms',
    'treat.alopecia.li4': 'Autoimmune-related hair shedding',
    'treat.alopecia.li5': 'Medical &amp; regenerative treatment options',
    // Radiant Skin keys
    'radiant.dermapen.desc': 'Advanced microneedling for collagen induction, scar revision &amp; skin rejuvenation',
    'radiant.dermapen.1': 'Stimulates collagen &amp; elastin production',
    'radiant.dermapen.2': 'Reduces fine lines, wrinkles &amp; acne scars',
    'radiant.dermapen.3': 'Improves skin texture &amp; tone',
    'radiant.dermapen.4': 'Minimal downtime with noticeable results',
    'radiant.hydracool.desc': 'Cooled hydra-dermabrasion for deep cleansing &amp; hydration',
    'radiant.hydracool.1': 'Patented cooled tip for maximum comfort',
    'radiant.hydracool.2': 'Deep pore cleansing &amp; extraction',
    'radiant.hydracool.3': 'Intense hydration infusion',
    'radiant.hydracool.4': 'Reduces redness &amp; inflammation',
    'radiant.nanofacial.desc': 'Nano-infusion facial for intensive skin repair',
    'radiant.nanofacial.1': 'Nano-infusion technology for deeper penetration',
    'radiant.nanofacial.2': 'Repairs damaged skin barrier',
    'radiant.nanofacial.3': 'Brightens &amp; evens skin tone',
    'radiant.nanofacial.4': 'Suitable for sensitive skin types',
    'radiant.vivace.desc': 'Radiofrequency microneedling for skin tightening',
    'radiant.vivace.1': 'Combines microneedling with radiofrequency energy',
    'radiant.vivace.2': 'Tightens loose skin &amp; reduces wrinkles',
    'radiant.vivace.3': 'Stimulates natural collagen production',
    'radiant.vivace.4': 'Minimal pain with faster recovery',
    'radiant.hydrafacial.desc': 'Gentle exfoliation &amp; deep hydration facial',
    'radiant.hydrafacial.1': 'Gentle exfoliation removes dead skin cells',
    'radiant.hydrafacial.2': 'Deep hydration &amp; nourishment',
    'radiant.hydrafacial.3': 'Improves skin clarity &amp; radiance',
    'radiant.hydrafacial.4': 'No downtime, immediate glow',
    'radiant.exosome.desc': 'Advanced regenerative exosome treatment for skin repair',
    'radiant.exosome.1': 'Advanced regenerative cell signaling',
    'radiant.exosome.2': 'Accelerates skin repair &amp; healing',
    'radiant.exosome.3': 'Reduces inflammation &amp; pigmentation',
    'radiant.exosome.4': 'Boosts collagen for long-term rejuvenation',
    'radiant.salmonDna.desc': 'Polynucleotide-based skin rejuvenation',
    'radiant.salmonDna.1': 'Polynucleotide-based skin regeneration',
    'radiant.salmonDna.2': 'Deep hydration &amp; elasticity improvement',
    'radiant.salmonDna.3': 'Reduces fine lines &amp; photoaging',
    'radiant.salmonDna.4': 'Natural biocompatible ingredients',
    'radiant.carboxy.desc': 'CO\u2082 injections for skin oxygenation &amp; rejuvenation',
    'radiant.carboxy.1': 'Medical CO\u2082 injections for oxygenation',
    'radiant.carboxy.2': 'Stimulates blood flow &amp; collagen',
    'radiant.carboxy.3': 'Reduces dark circles &amp; under-eye bags',
    'radiant.carboxy.4': 'Improves skin firmness &amp; elasticity',
    'radiant.chemicalPeels.desc': 'Professional-grade chemical peels for various skin concerns',
    'radiant.chemicalPeels.1': 'Medical-grade peel solutions',
    'radiant.chemicalPeels.2': 'Targets acne, pigmentation &amp; aging',
    'radiant.chemicalPeels.3': 'Customizable strength &amp; formulation',
    'radiant.chemicalPeels.4': 'Reveals fresh, radiant skin',
    'radiant.inquire': 'Inquire on WhatsApp',
    'radiant.book': 'Book Now',
    'radiant.cta.title': 'Not Sure Which Treatment Is Right for You?',
    'radiant.cta.desc': 'Book a consultation with our expert dermatologists and we\'ll create a personalized treatment plan tailored to your skin.',
    'radiant.cta.book': 'Book a Consultation',
    'radiant.cta.whatsapp': 'Chat on WhatsApp',
    // Body Contouring keys
    'fatDissolving.desc': 'Non-surgical fat reduction injections for targeted areas such as the abdomen, thighs, love handles, and chin. This minimally invasive treatment breaks down fat cells naturally, helping you achieve a slimmer, more sculpted silhouette without downtime.',
    'fatDissolving.l1': 'Targeted fat reduction',
    'fatDissolving.l2': 'Minimally invasive with no downtime',
    'fatDissolving.l3': 'Natural-looking, gradual results',
    'fatDissolving.l4': 'Suitable for chin, abdomen, thighs &amp; love handles',
    'btlExilis.desc': 'A cutting-edge non-invasive radiofrequency and ultrasound treatment that tightens skin, reduces fat, and contours the body. BTL Exilis Ultra delivers controlled energy to deeply heat tissue, stimulating collagen production and reducing fat cells for visible, lasting results.',
    'btlExilis.l1': 'Non-invasive radiofrequency + ultrasound',
    'btlExilis.l2': 'Skin tightening and fat reduction in one session',
    'btlExilis.l3': 'Safe, comfortable, no downtime',
    'btlExilis.l4': 'Ideal for abdomen, arms, thighs &amp; buttocks',
    'collagenStim.desc': 'Biostimulatory treatments that promote natural collagen production to improve skin firmness, elasticity, and body contour. These injectable treatments work gradually to restore structural support, giving your skin a tighter, more youthful appearance across the body.',
    'collagenStim.l1': 'Natural collagen stimulation',
    'collagenStim.l2': 'Improves skin firmness &amp; elasticity',
    'collagenStim.l3': 'Long-lasting, gradual results',
    'collagenStim.l4': 'Effective for buttocks, arms, abdomen &amp; thighs',
    'doubleChin.desc': 'Non-surgical double chin reduction using advanced injectable treatments that break down fat cells under the chin. This quick, comfortable procedure effectively reduces submental fat, enhancing your jawline profile and restoring facial harmony without surgery.',
    'doubleChin.l1': 'Non-surgical submental fat reduction',
    'doubleChin.l2': 'Quick procedure with minimal discomfort',
    'doubleChin.l3': 'Noticeable results within weeks',
    'doubleChin.l4': 'Enhances jawline definition',
    // Laser Hair Removal keys
    'laserHair.desc': 'Our advanced laser hair removal system delivers safe, effective, permanent hair reduction for men and women of all skin types. Using state-of-the-art laser technology with integrated cooling, treatments are virtually pain-free and designed for optimal comfort. Whether you\'re looking to treat small areas or the entire body, our expert team creates a customized treatment plan tailored to your skin type and hair colour.',
    'laserHair.l1': 'Safe and effective permanent hair reduction',
    'laserHair.l2': 'Suitable for all skin types, including dark skin',
    'laserHair.l3': 'Advanced cooling technology for pain-free treatment',
    'laserHair.l4': 'Treats face, underarms, arms, legs, bikini, chest, back &amp; full body',
    'laserHair.l5': 'Custom treatment plans for optimal results',
    'laserRejuv.desc': 'Non-ablative laser treatment that stimulates collagen production and resurfaces the skin to reduce fine lines, wrinkles, sun damage, and uneven texture. Restore your skin\'s natural radiance with minimal downtime.',
    'laserRejuv.l1': 'Stimulates natural collagen production',
    'laserRejuv.l2': 'Reduces fine lines, wrinkles &amp; sun damage',
    'laserRejuv.l3': 'Improves skin texture &amp; radiance',
    'laserRejuv.l4': 'Minimal downtime, gradual natural results',
    'pigmentation.desc': 'Advanced laser and light-based treatments that target excess melanin to correct hyperpigmentation, melasma, sun spots, age spots, and post-inflammatory pigmentation. Achieve a more even, uniform skin tone with our customized protocols.',
    'pigmentation.l1': 'Targets melasma, sun spots &amp; age spots',
    'pigmentation.l2': 'Corrects post-inflammatory hyperpigmentation',
    'pigmentation.l3': 'Customized for all skin tones',
    'pigmentation.l4': 'Even, radiant skin tone results',
    'tightening.desc': 'Non-invasive laser and radiofrequency skin tightening treatments that stimulate collagen and elastin production to firm sagging skin on the face, neck, abdomen, arms, and thighs. Enjoy a lifted, youthful contour without surgery.',
    'tightening.l1': 'Non-invasive skin firming &amp; lifting',
    'tightening.l2': 'Stimulates collagen &amp; elastin production',
    'tightening.l3': 'Effective for face, neck, abdomen, arms &amp; thighs',
    'tightening.l4': 'No downtime, natural-looking lift',
    'treat.laserRejuv': 'Laser Skin Rejuvenation',
    'treat.pigmentation': 'Pigmentation Correction',
    'treat.skinTightening': 'Skin Tightening',
  };

  const arText = {
    'top.location': 'السالمية، الكويت',
    'top.hours': 'السبت – الخميس: ١٠:٠٠ ص – ٨:٠٠ م',
    'top.whatsapp': 'واتساب',
    'nav.home': 'الرئيسية',
    'nav.about': 'من نحن',
    'nav.services': 'الخدمات',
    'nav.treatments': 'العلاجات',
    'nav.specialists': 'الأطباء',
    'nav.gallery': 'معرض الصور',
    'nav.testimonials': 'آراء المرضى',
    'nav.contact': 'اتصل بنا',
    'nav.book': 'احجز الآن',
    'menu.faceSkin': 'الوجه والبشرة',
    'menu.radiantSkin': 'البشرة المشعة',
    'menu.bodyContouring': 'تنحيف الجسم',
    'menu.laserHair': 'إزالة الشعر بالليزر',
    'hero.badge': 'السالمية، الكويت',
    'hero.sub': 'طب جلدية متقدم وعلاجات تجميلية وليزر في قلب السالمية.<br>رحلتك لبشرة مشرقة وصحية تبدأ هنا.',
    'hero.cta1': 'احجز موعد',
    'hero.whatsapp': 'راسلنا واتساب',
    'about.tag': 'مرحباً بكم في',
    'about.title': 'مجمع الهلال الدولي',
    'about.desc': 'وجهتك الموثوقة لطب الجلدية والتجميل الراقي في السالمية، الكويت. نحن نجمع بين التميز الطبي وتجربة فاخرة للمرضى.',
    'about.exp': 'عاماً من التميز',
    'about.p1': 'في مجمع الهلال الدولي، نحن ملتزمون بتقديم رعاية تجميلية وجلدية عالمية المستوى مصممة خصيصاً لتلبية احتياجات مرضانا في الكويت. يقود عيادتنا فريق من الأخصائيين المؤهلين تأهيلاً عالياً وذوي خبرة واسعة في طب الجلدية الطبية والتجميلية.',
    'about.p2': 'من العلاجات المتقدمة بالليزر إلى الحقن التجميلية وطب الجلدية الطبي، يتم تنفيذ كل إجراء بدقة متناهية باستخدام أحدث التقنيات وأعلى معايير السلامة. نحن نؤمن بالنتائج الطبيعية التي تعزز ثقتك بنفسك ورفاهيتك.',
    'about.stat1': 'مريض سعيد',
    'about.stat2': 'عاماً خبرة',
    'about.stat3': 'علاج',
    'why.tag': 'لماذا تختارنا',
    'why.title': 'فرق الهلال الدولي',
    'why.card1.title': 'قيادة خبراء',
    'why.card1.text': 'يقودها أطباء جلدية معتمدون من مجالس دولية مع خبرة واسعة في الطب التجميلي.',
    'why.card2.title': 'أحدث التقنيات',
    'why.card2.text': 'أحدث ابتكارات طب الجلدية والليزر لإجراءات آمنة وفعالة وموثوقة.',
    'why.card3.title': 'رعاية شخصية',
    'why.card3.text': 'خطط علاج مخصصة لنوع بشرتك واهتماماتك وأهدافك الجمالية الفريدة.',
    'why.card4.title': 'نتائج مثبتة',
    'why.card4.text': 'موثوق من آلاف المرضى الراضين عن نتائج طبيعية ومتميزة.',
    'why.card5.title': 'تجربة فاخرة',
    'why.card5.text': 'راحة وخصوصية راقية في بيئة متطورة ومرحبة.',
    'why.card6.title': 'موقع متميز',
    'why.card6.text': 'يقع في السالمية بشكل ملائم، ويمكن الوصول إليه بسهولة من جميع مناطق الكويت.',
    'services.tag': 'خبرتنا',
    'services.title': 'خدمات تجميلية وجلدية شاملة',
    'services.desc': 'من الحقن إلى الليزر، نقدم مجموعة كاملة من العلاجات المتقدمة المصممة خصيصاً لاحتياجاتك.',
    'services.cat1': 'الحقن التجميلية',
    'services.cat1.desc': 'البوتوكس والحشوات الجلدية ومعززات البشرة وعلاجات الحقن المتقدمة لتجديد الشباب الطبيعي.',
    'services.cat2': 'علاجات الليزر',
    'services.cat2.desc': 'إزالة الشعر بالليزر المتقدم وتجديد البشرة وعلاج التصبغات وشد الجلد.',
    'services.cat3': 'طب الجلدية الطبي',
    'services.cat3.desc': 'تشخيص وعلاج حب الشباب والأكزيما والصدفية والتهابات الجلد وجميع الحالات الجلدية.',
    'services.cat4': 'تجديد البشرة',
    'services.cat4.desc': 'التقشير الكيميائي والميكرونيدلينغ والهايدرا فيشل والعلاجات المتقدمة لإنعاش البشرة.',
    'services.view': 'عرض التفاصيل',
    'services.pageTitle': 'خدماتنا الشاملة',
    'services.pageDesc': 'من الحقن المتقدمة إلى طب الجلدية الطبي، كل علاج مصمم خصيصاً لاحتياجاتك الفريدة.',
    'treatments.tag': 'العلاجات',
    'treatments.title': 'استكشف مجموعتنا الكاملة من العلاجات',
    'treatments.desc': 'يتم تنفيذ كل علاج على يد فريقنا الخبير باستخدام أحدث التقنيات الطبية.',
    'treatments.allBtn': 'عرض جميع العلاجات',
    'filter.all': 'الكل',
    'filter.injectables': 'الحقن',
    'filter.laser': 'الليزر',
    'filter.skin': 'العناية بالبشرة',
    'filter.body': 'الجسم',
    'filter.botox': 'بوتوكس',
    'filter.fillers': 'حشوات',
    'gallery.tag': 'النتائج',
    'gallery.title': 'قبل وبعد',
    'gallery.desc': 'نتائج حقيقية لمرضانا. كل تحول يعكس التزامنا بالتميز.',
    'gallery.botox': 'بوتوكس الجبهة',
    'gallery.fillers': 'حشوات الشفاه',
    'gallery.laser': 'إزالة الشعر بالليزر',
    'gallery.skin': 'علاج حب الشباب',
    'gallery.jawline': 'تحديد الفك',
    'gallery.neck': 'بوتوكس الرقبة',
    'gallery.pigmentation': 'علاج التصبغات',
    'gallery.rejuvenation': 'تجديد البشرة',
    'testimonials.tag': 'آراء المرضى',
    'testimonials.title': 'ماذا يقول مرضانا',
    'testimonial.1': '"رعاية استثنائية من أول لحظة. د. الراشد أخذ وقته لفهم مخاوفي والنتائج تجاوزت توقعاتي. عيادة عالمية المستوى حقاً."',
    'testimonial.1t': 'علاج بوتوكس',
    'testimonial.2': '"أزور الهلال منذ أكثر من عام لإزالة الشعر بالليزر والنتائج مذهلة. الفريق محترف وودود ويجعلك تشعرين بالراحة التامة."',
    'testimonial.2t': 'إزالة الشعر بالليزر',
    'testimonial.3': '"علاج التقشير الكيميائي غير بشرتي تماماً. لم أشعر بثقة أكبر من قبل. شكراً لفريق الهلال على خبرتكم واهتمامكم."',
    'testimonial.3t': 'تقشير كيميائي',
    'testimonial.4': '"احترافية ونظافة ونتائج مضمونة. علاج الحشوات يبدو طبيعياً تماماً - تماماً ما أردته. أنصح بشدة بمجمع الهلال."',
    'testimonial.4t': 'حشوات تجميلية',
    'testimonial.5': '"أفضل عيادة جلدية في الكويت. د. فاطمة ساعدتني في السيطرة على الأكزيما عندما فشل الآخرون. أخيراً استعدت بشرتي. ممتنة للأبد."',
    'testimonial.5t': 'طب جلدية طبي',
    'contact.tag': 'تواصل معنا',
    'contact.title': 'احجز موعدك',
    'contact.desc': 'مستعد لبدء رحلتك؟ اتصل بنا أو املأ النموذج وسنعود إليك قريباً.',
    'contact.call': 'اتصل بنا',
    'contact.whatsapp': 'واتساب',
    'contact.location': 'الموقع',
    'contact.location.text': 'السالمية، الكويت',
    'contact.hours': 'ساعات العمل',
    'contact.hours.text': 'السبت – الخميس: ١٠:٠٠ ص – ٨:٠٠ م<br>الجمعة: مغلق',
    'contact.hours.short': 'السبت – الخميس: ١٠ ص – ٨ م',
    'form.name': 'الاسم الكامل *',
    'form.phone': 'رقم الهاتف *',
    'form.email': 'البريد الإلكتروني',
    'form.service': 'الخدمة المطلوبة *',
    'form.select': 'اختر خدمة',
    'form.message': 'الرسالة *',
    'form.submit': 'إرسال الرسالة',
    'footer.desc': 'مجمع الهلال الدولي هو مركز رائد لطب الجلدية والتجميل في السالمية، الكويت، يقدم علاجات جلدية وتجميلية متقدمة وآمنة وشخصية.',
    'footer.quick': 'روابط سريعة',
    'footer.treatments': 'العلاجات',
    'footer.contact': 'اتصل بنا',
    'footer.rights': 'جميع الحقوق محفوظة.',
    'specialists.tag': 'فريقنا',
    'specialists.title': 'تعرف على أخصائيينا الخبراء',
    'specialists.desc': 'محترفون مؤهلون تأهيلاً عالياً مكرسون لصحة بشرتك وأهدافك الجمالية.',
    'specialists.role1': 'المدير الطبي واستشاري الأمراض الجلدية',
    'specialists.role2': 'أخصائي الطب التجميلي',
    'specialists.role3': 'استشاري أمراض جلدية أول',
    'specialists.role4': 'أخصائي الليزر والتجميل',
    'specialists.bio1': 'طبيب جلدية معتمد من البورد مع أكثر من ١٥ عاماً من الخبرة في طب الجلدية الطبي والتجميلي، معترف به دولياً للتميز في رعاية المرضى.',
    'specialists.bio2': 'خبير في علاجات الحقن والليزر والإجراءات التجميلية المتقدمة مع أكثر من ١٠ سنوات خبرة وتدريب دولي.',
    'specialists.bio3': 'متخصص في طب الجلدية الطبي وفحص سرطان الجلد وإدارة الأمراض الجلدية المزمنة بنهج يركز على المريض.',
    'specialists.bio4': 'خبير في علاجات الليزر وتجديد البشرة وتنحيف الجسم مع تدريب وشهادات دولية متقدمة.',
    'specialists.cred1': 'البورد العربي لطب الجلدية',
    'specialists.cred1b': 'زميل الأكاديمية الأمريكية لطب الجلدية',
    'specialists.cred2': 'البورد الأمريكي للطب التجميلي',
    'specialists.cred2b': 'أخصائي ليزر معتمد',
    'specialists.cred3': 'الهيئة الطبية الكويتية',
    'specialists.cred3b': 'الأكاديمية الأوروبية لطب الجلدية',
    'specialists.cred4': 'معهد الليزر الدولي',
    'specialists.cred4b': 'ممارس تجميل معتمد',
    // Treatments
    'treat.botox': 'بوتوكس ودايسبورت',
    'treat.botox.desc': 'خبراء في تقليل التجاعيد بالبوتوكس والدايسبورت. تنعيم الخطوط الدقيقة وتجاعيد الجبهة وحول العينين للحصول على مظهر طبيعي منعش.',
    'treat.masseter': 'بوتوكس عضلة المضغ',
    'treat.skinBooster': 'معزز البشرة عالي الفعالية',
    'treat.nefertiti': 'رفع نفرتيتي (الرقبة والفك)',
    'treat.hyperhidrosis': 'فرط التعرق',
    'treat.eyelid': 'رفع الجفن',
    'treat.neckTight': 'شد الرقبة',
    'treat.cheeks': 'الخدود والذقن والشفاه والصدغين',
    'treat.nasolabial': 'الخطوط الأنفية الشفوية',
    'treat.radiesse': 'رادييس',
    'treat.nose': 'تجديد الأنف غير الجراحي',
    'treat.profhilo': 'بروفيلو',
    'treat.polynucleotides': 'بولينوكليوتيدات',
    'treat.sculptra': 'سكلبترا',
    'treat.prpMicro': 'الميكرونيدلينغ بالـ PRP والإكسوزوم',
    'treat.prpMicro.desc': 'علاج البلازما الغنية بالصفائح الدموية والميكرونيدلينغ المتقدم لتحفيز الكولاجين الطبيعي وتجديد البشرة.',
    'treat.rfMicro': 'الميكرونيدلينغ بالترددات الراديوية',
    'treat.doubleChin': 'الذقن المزدوجة',
    'treat.meso': 'الميزوثيرابي للدهون والشد',
    'treat.jawline': 'تحديد خط الفك',
    'treat.fillerDissolve': 'إذابة الحشوات',
    'treat.corrective': 'العلاجات التصحيحية',
    'treat.skinTags': 'الزوائد الجلدية والشامات',
    'treat.prpConc': 'مركز PRP',
    'treat.hairLab': 'التشخيص المختبري لتساقط الشعر',
    'treat.exosomalDermapen': 'إكسوزومال ديرمابين',
    'treat.medicalMeso': 'الميزوثيرابي الطبي',
    'treat.alopecia': 'علاج الثعلبة',
    'treat.fillers': 'الحشوات الجلدية',
    'treat.fillers.desc': 'استعادة الحجم وتعزيز الملامح وتجديد مظهرك بحشوات جلدية فاخرة للشفاه والخدود والذقن والمزيد.',
    'treat.laserHair': 'إزالة الشعر بالليزر',
    'treat.laserHair.desc': 'إزالة شعر دائمة بتقنية الليزر المتقدمة. آمنة وفعالة ومناسبة لجميع أنواع البشرة.',
    'treat.chemicalPeels': 'التقشير الكيميائي والوجه',
    'treat.chemicalPeels.desc': 'تقشير كيميائي احترافي وعلاجات وجه متقدمة لبشرة مشرقة وصحية.',
    'treat.dermapen': 'ديرمابين / ميكرونيدلينغ',
    'treat.hydracool': 'هايدرا كول',
    'treat.nanofacial': 'نانو فيشل',
    'treat.vivace': 'فيفاس ميكرونيدلينغ',
    'treat.hydrafacial': 'ميكروديرمابريشن / هايدرا فيشل',
    'treat.exosome': 'الإكسوزوم',
    'treat.salmonDna': 'حمض السلمون النووي',
    'treat.carboxy': 'علاج الكربوكسي',
    'treat.fatDissolving': 'حقن إذابة الدهون',
    'treat.btlExilis': 'BTL إكسيلس ألترا',
    'treat.collagenStim': 'محفزات الكولاجين',
    'treat.bodyContour': 'تنحيف الجسم',
    'treat.bodyContour.desc': 'تنحيف غير جراحي وتقليل الدهون للحصول على قوام أكثر تناسقاً.',
    'treat.skinRejuv': 'تجديد البشرة',
    // Services page
    'serv.injectables': 'الحقن التجميلية',
    'serv.injectables.desc': 'علاجات حقن فاخرة تشمل البوتوكس والحشوات الجلدية ومعززات البشرة لنتائج طبيعية متجددة.',
    'serv.laser': 'علاجات الليزر',
    'serv.laser.desc': 'تقنية ليزر متطورة لإزالة الشعر وتجديد البشرة وعلاج التصبغات وشد الجلد.',
    'serv.laser.rejuv': 'تجديد البشرة بالليزر',
    'serv.laser.pigment': 'تصحيح التصبغات',
    'serv.laser.tighten': 'شد الجلد',
    'serv.laser.vascular': 'علاج الآفات الوعائية',
    'serv.dermatology': 'طب الجلدية الطبي',
    'serv.dermatology.desc': 'تشخيص وعلاج جميع الحالات الجلدية على يد أخصائيينا المعتمدين.',
    'serv.derm.acne': 'علاج حب الشباب وآثاره',
    'serv.derm.eczema': 'الأكزيما والصدفية',
    'serv.derm.infection': 'التهابات الجلد',
    'serv.derm.screening': 'فحص سرطان الجلد',
    'serv.derm.allergy': 'الحساسيات الجلدية',
    'serv.skinRejuv': 'تجديد البشرة',
    'serv.skinRejuv.desc': 'علاجات متقدمة لإنعاش واستعادة إشراق بشرتك الطبيعي ومظهرها الشبابي.',
    'serv.skinRejuv.antiAge': 'حلول مكافحة الشيخوخة',
    'serv.skinRejuv.prp': 'فيشل PRP',
    'serv.bodyContour': 'تنحيف الجسم',
    'serv.bodyContour.desc': 'تنحيف غير جراحي وتقليل الدهون للحصول على قوام أكثر تناسقاً وثقة.',
    'serv.consultation': 'استشارات عامة',
    'serv.consultation.desc': 'استشارات شاملة مع أخصائيي الجلدية لتقييم احتياجاتك ووضع خطة علاج مخصصة.',
    'serv.consult.skin': 'تحليل كامل للبشرة',
    'serv.consult.hair': 'تقييم الشعر وفروة الرأس',
    'serv.consult.aesthetic': 'استشارة تجميلية',
    'serv.consult.custom': 'خطة علاج مخصصة',
    // Page & breadcrumb keys
    'breadcrumb.home': 'الرئيسية',
    'breadcrumb.treatments': 'العلاجات',
    'breadcrumb.faceSkin': 'الوجه والبشرة',
    'breadcrumb.radiantSkin': 'البشرة المشعة',
    'breadcrumb.bodyContour': 'تنحيف الجسم',
    'breadcrumb.laserHair': 'إزالة الشعر بالليزر',
    'faceSkin.pageTitle': 'علاجات الوجه والبشرة',
    'faceSkin.pageDesc': 'الحقن المتقدمة وتجديد البشرة وعلاجات الوجه التجميلية المصممة لتعزيز جمالك الطبيعي في مجمع الهلال الدولي.',
    'faceSkin.tag': 'خبرتنا',
    'faceSkin.sectionTitle': 'علاجات شاملة للوجه والبشرة',
    'faceSkin.sectionDesc': 'يتم تنفيذ كل علاج على يد فريقنا الطبي الخبير باستخدام منتجات فاخرة وأحدث التقنيات لنتائج طبيعية تدوم طويلاً.',
    'faceSkin.bookingText': 'لست متأكداً من العلاج المناسب لك؟ احجز استشارة مع أخصائيينا اليوم.',
    'faceSkin.bookingWA': 'احجز عبر واتساب',
    'faceSkin.bookingForm': 'احجز موعد',
    'radiant.pageTitle': 'علاجات البشرة المشعة',
    'radiant.pageDesc': 'علاجات متقدمة لتجديد البشرة مصممة لاستعادة إشراق بشرتك الطبيعي وملمسها وحيويتها.',
    'bodyContouring.pageTitle': 'تنحيف الجسم',
    'bodyContouring.pageDesc': 'علاجات نحت الجسم غير الجراحية وتقليل الدهون للحصول على قوام أكثر تناسقاً وثقة.',
    'laserHair.pageTitle': 'إزالة الشعر بالليزر',
    'laserHair.pageDesc': 'إزالة شعر دائمة وآمنة وفعالة باستخدام تقنية الليزر المتقدمة. مناسبة لجميع أنواع البشرة.',
    'td.enquire': 'استفسر عبر واتساب',
    'td.book': 'احجز استشارة',
    // Face & Skin treatment descs & list items
    'treat.masseter.desc': 'حقن البوتوكس المستهدف في عضلات المضغ لتحديد الفك وتخفيف صرير الأسنان. يعمل هذا العلاج على تنحيف الفك المربع وإنشاء مظهر وجه أكثر تناسقاً مع تخفيف آلام الصداع الناتج عن التوتر ومشاكل المفصل الصدغي الفكي.',
    'treat.masseter.li1': 'تنحيف الفك وتحديد الشكل البيضاوي',
    'treat.masseter.li2': 'تخفيف صرير الأسنان (طحن الأسنان)',
    'treat.masseter.li3': 'آلام المفصل الصدغي الفكي والصداع',
    'treat.masseter.li4': 'تصحيح عدم تناسق الوجه',
    'treat.masseter.li5': 'تنحيف الوجه غير الجراحي',
    'treat.skinBooster.desc': 'معززات البشرة عالية الفعالية هي علاجات حقن متقدمة توفر مزيجاً قوياً من حمض الهيالورونيك والأحماض الأمينية والفيتامينات ومضادات الأكسدة في عمق الأدمة. تعمل هذه المعززات على ترطيب البشرة من الداخل، وتحفيز إنتاج الكولاجين وتحسين المرونة.',
    'treat.skinBooster.li1': 'ترطيب عميق ونفخ البشرة',
    'treat.skinBooster.li2': 'تحفيز الكولاجين والإيلاستين',
    'treat.skinBooster.li3': 'تقليل الخطوط الدقيقة والتجاعيد',
    'treat.skinBooster.li4': 'تحسين ملمس البشرة وإشراقها',
    'treat.skinBooster.li5': 'البشرة الباهتة والمتعبة والجافة',
    'treat.nefertiti.desc': 'رفع نفرتيتي هو تقنية غير جراحية لتجديد الرقبة والفك باستخدام حقن البوتوكس الاستراتيجية. من خلال إرخاء حزم العضلات الرقبية والعضلات الخافضة للفك، يخلق العلاج تأثير رفع وشد مرئي.',
    'treat.nefertiti.li1': 'تقليل حزم العضلات الرقبية',
    'treat.nefertiti.li2': 'تحديد ورفع خط الفك',
    'treat.nefertiti.li3': 'شد وتحديد الرقبة',
    'treat.nefertiti.li4': 'تنعيم خطوط الماريونيت',
    'treat.nefertiti.li5': 'رفع الوجه السفلي غير الجراحي',
    'treat.hyperhidrosis.desc': 'يمكن علاج فرط التعرق بفعالية باستخدام حقن البوتوكس في الإبطين والراحتين والأخمصين أو الجبهة. يمنع البوتوكس الإشارات الكيميائية التي تحفز الغدد العرقية، مما يقلل التعرق بشكل كبير.',
    'treat.hyperhidrosis.li1': 'التعرق المفرط تحت الإبطين',
    'treat.hyperhidrosis.li2': 'فرط تعرق الراحتين',
    'treat.hyperhidrosis.li3': 'فرط تعرق الأخمصين',
    'treat.hyperhidrosis.li4': 'احمرار وتعرق الوجه',
    'treat.hyperhidrosis.li5': 'تقليل التعرق طويل الأمد (٦–١٢ شهراً)',
    'treat.eyelid.desc': 'رفع الجفن غير الجراحي يستخدم حقن البوتوكس المستهدفة حول الحاجب والعين لفتح العينين وإنشاء مظهر أكثر شباباً. يعمل على رفع الحاجبين وتنعيم تجاعيد قدم الغراب.',
    'treat.eyelid.li1': 'تدلي الجفون العلوية',
    'treat.eyelid.li2': 'تدلي الحاجبين',
    'treat.eyelid.li3': 'الخطوط الدقيقة حول العينين وقدم الغراب',
    'treat.eyelid.li4': 'عدم تناسق مظهر العينين',
    'treat.eyelid.li5': 'العيون المتعبة والثقيلة المظهر',
    'treat.neckTight.desc': 'تجمع علاجات شد الرقبة بين الليزر أو الترددات الراديوية أو الحقن لشد وتجديد الجلد المترهل في الرقبة ومنطقة الصدر. تحفز هذه الوسائل غير الجراحية إعادة بناء الكولاجين والإيلاستين.',
    'treat.neckTight.li1': 'جلد الرقبة المترهل',
    'treat.neckTight.li2': 'خطوط الرقبة الأفقية (رقبة التقنية)',
    'treat.neckTight.li3': 'فقدان تحديد خط الفك',
    'treat.neckTight.li4': 'رقبة الديك الرومي / الذقن المزدوجة',
    'treat.neckTight.li5': 'شد الجلد غير الجراحي',
    'treat.cheeks.desc': 'الحشوات الجلدية الفاخرة تستعيد الحجم المفقود وتعزز ملامح الوجه وتجدده في أي عمر. باستخدام حشوات حمض الهيالورونيك، يمكن لأخصائيينا تكبير عظام الخد وتحديد الذقن ونفخ الشفاه.',
    'treat.cheeks.li1': 'الخدود الغائرة وفقدان حجم منتصف الوجه',
    'treat.cheeks.li2': 'تحسين وتحديد الشفاه',
    'treat.cheeks.li3': 'تكبير الذقن وإسقاطه',
    'treat.cheeks.li4': 'تجويف الصدغين',
    'treat.cheeks.li5': 'تصحيح عدم تناسق الوجه',
    'treat.nasolabial.desc': 'الخطوط الأنفية الشفوية تتعمق مع تقدم العمر. تعمل حقن الحشوات الجلدية على تنعيم هذه الخطوط بأمان عن طريق استعادة الحجم والدعم لمنتصف الوجه.',
    'treat.nasolabial.li1': 'الخطوط الأنفية الشفوية العميقة (خطوط الابتسامة)',
    'treat.nasolabial.li2': 'فقدان حجم منتصف الوجه',
    'treat.nasolabial.li3': 'خطوط الماريونيت',
    'treat.nasolabial.li4': 'مظهر الوجه المتعب أو الهزيل',
    'treat.nasolabial.li5': 'تجديد منتصف الوجه غير الجراحي',
    'treat.radiesse.desc': 'رادييس هو حشو محفز حيوي فريد مصنوع من كريات هيدروكسي أباتيت الكالسيوم. يوفر تصحيحاً فورياً للحجم مع تحفيز إنتاج الكولاجين الخاص بك.',
    'treat.radiesse.li1': 'الخطوط الأنفية الشفوية العميقة وخطوط الماريونيت',
    'treat.radiesse.li2': 'حجم الخدود ورفعها',
    'treat.radiesse.li3': 'تحديد الفك والذقن',
    'treat.radiesse.li4': 'تجديد اليدين',
    'treat.radiesse.li5': 'تحفيز الكولاجين الطبيعي',
    'treat.nose.desc': 'تجميل الأنف غير الجراحي يستخدم الحشوات الجلدية لإعادة تشكيل وتنقيح الأنف بدون جراحة. يمكن للحشوات تنعيم سنام الظهر ورفع طرف الأنف وتصحيح عدم التناسق.',
    'treat.nose.li1': 'إخفاء سنام الظهر الأنفي',
    'treat.nose.li2': 'رفع وتنقيح طرف الأنف',
    'treat.nose.li3': 'تصحيح عدم تناسق الأنف',
    'treat.nose.li4': 'تكبير جسر الأنف',
    'treat.nose.li5': 'موازنة المظهر الجانبي غير الجراحي',
    'treat.profhilo.desc': 'بروفيلو هو علاج حقن ثوري يجمع بين حمض الهيالورونيك عالي التركيز مع تقنية تشتيت فريدة لترطيب الأنسجة العميقة وإعادة تشكيل الكولاجين.',
    'treat.profhilo.li1': 'ترهل الجلد وفقدان المرونة',
    'treat.profhilo.li2': 'البشرة الجافة والباهتة',
    'treat.profhilo.li3': 'الخطوط الدقيقة والملمس المتجعد',
    'treat.profhilo.li4': 'تجديد اليدين',
    'treat.profhilo.li5': 'تحسين جودة البشرة بشكل عام',
    'treat.polynucleotides.desc': 'علاجات البولينوكليوتيد تستخدم شظايا الحمض النووي النقية لتحفيز تجديد الخلايا وإصلاح الأنسجة. تغذي هذه الحقن البشرة بعمق وتعزز تخليق الكولاجين.',
    'treat.polynucleotides.li1': 'الخطوط الدقيقة وشيخوخة البشرة',
    'treat.polynucleotides.li2': 'الهالات السوداء تحت العينين والتجاويف',
    'treat.polynucleotides.li3': 'ندبات حب الشباب والمشاكل النسيجية',
    'treat.polynucleotides.li4': 'البشرة الجافة والتالفة',
    'treat.polynucleotides.li5': 'تجديد وإصلاح البشرة',
    'treat.sculptra.desc': 'سكلبترا هو حقن محفز حيوي مصنوع من حمض البولي-إل-لاكتيك الذي يستعيد حجم الوجه تدريجياً عن طريق تحفيز إنتاج الكولاجين الخاص بك.',
    'treat.sculptra.li1': 'فقدان حجم الوجه المرتبط بالعمر',
    'treat.sculptra.li2': 'الخدود والصدغين الغائرة',
    'treat.sculptra.li3': 'الخطوط الأنفية الشفوية وخطوط الماريونيت',
    'treat.sculptra.li4': 'إعادة تشكيل الفك والذقن',
    'treat.sculptra.li5': 'تجديد الكولاجين الطبيعي التدريجي',
    'treat.prpMicro.li1': 'ندبات حب الشباب والمسامات المتوسعة',
    'treat.prpMicro.li2': 'الخطوط الدقيقة والتجاعيد',
    'treat.prpMicro.li3': 'لون البشرة الباهت وغير المتجانس',
    'treat.prpMicro.li4': 'علامات التمدد والندبات',
    'treat.prpMicro.li5': 'تجديد البشرة الشامل وتحفيز الكولاجين',
    'treat.rfMicro.desc': 'الميكرونيدلينغ بالترددات الراديوية يجمع بين قوة تحفيز الكولاجين للميكرونيدلينغ مع طاقة شد الجلد للترددات الراديوية. إبر فائقة الدقة تخترق الأدمة وتوفر حرارة RF محكومة.',
    'treat.rfMicro.li1': 'ترهل الجلد وفقدان المرونة',
    'treat.rfMicro.li2': 'ندبات حب الشباب والندبات العميقة',
    'treat.rfMicro.li3': 'المسامات المتوسعة والمشاكل النسيجية',
    'treat.rfMicro.li4': 'الخطوط الدقيقة وترهل الفك السفلي',
    'treat.rfMicro.li5': 'شد الوجه والرقبة غير الجراحي',
    'treat.doubleChin.desc': 'يمكن تقليل الدهون تحت الذقن بشكل فعال باستخدام علاجات غير جراحية كحقن حمض ديوكسيكوليك أو تحلل الدهون بالليزر.',
    'treat.doubleChin.li1': 'الدهون تحت الذقن (الذقن المزدوجة)',
    'treat.doubleChin.li2': 'ضعف تحديد خط الفك',
    'treat.doubleChin.li3': 'الامتلاء تحت الذقن',
    'treat.doubleChin.li4': 'تحديد الذقن غير الجراحي',
    'treat.doubleChin.li5': 'تقليل الدهون الدائم',
    'treat.meso.desc': 'الميزوثيرابي هو حقن مجهري لمزيج مخصص من الفيتامينات والإنزيمات والأحماض الأمينية والمركبات حالّة للدهون مباشرة في طبقة الأدمة.',
    'treat.meso.li1': 'الدهون الموضعية',
    'treat.meso.li2': 'تقليل السيلوليت',
    'treat.meso.li3': 'ترهل الجلد وضعف النغمة',
    'treat.meso.li4': 'تنحيف وتحديد الوجه',
    'treat.meso.li5': 'نحت الجسم بدون جراحة',
    'treat.jawline.desc': 'تحديد الفك باستخدام الحشوات الجلدية لنحت وتعزيز محيط الفك السفلي، مما يخلق فكاً أكثر حدة وجمالاً.',
    'treat.jawline.li1': 'الفك الضعيف أو غير المحدد',
    'treat.jawline.li2': 'نقص بروز الذقن',
    'treat.jawline.li3': 'عدم تناسق الفك',
    'treat.jawline.li4': 'ترهل الفك المرتبط بالعمر',
    'treat.jawline.li5': 'تذكير / تأنيث الوجه غير الجراحي',
    'treat.fillerDissolve.desc': 'حقن الهيالورونيداز تذيب الحشوات غير المرغوب بها أو الزائدة بسرعة وأمان. سواء كان لديك تكتلات أو عدم تناسق أو هجرة للحشو.',
    'treat.fillerDissolve.li1': 'مناطق مليئة بشكل زائد أو متكتلة',
    'treat.fillerDissolve.li2': 'عدم تناسق أو هجرة الحشو',
    'treat.fillerDissolve.li3': 'تأثير تيندال (لون مزرق)',
    'treat.fillerDissolve.li4': 'نتائج حشو غير مرضية',
    'treat.fillerDissolve.li5': 'علاج طارئ لانسداد الأوعية الدموية',
    'treat.corrective.desc': 'تعالج علاجاتنا التصحيحية مجموعة واسعة من مشاكل البشرة بما في ذلك فرط التصبغ والكلف والاحمرار التالي للالتهاب وأضرار الشمس.',
    'treat.corrective.li1': 'فرط التصبغ والكلف',
    'treat.corrective.li2': 'الاحمرار التالي للالتهاب',
    'treat.corrective.li3': 'بقع الشمس وشيخوخة الجلد الضوئية',
    'treat.corrective.li4': 'لون البشرة غير المتجانس والملمس',
    'treat.corrective.li5': 'خطط العناية التصحيحية الطبية',
    'treat.skinTags.desc': 'نقدم إزالة آمنة وفعالة للزوائد الجلدية والشامات والثآليل والتقرنات الدهنية باستخدام الليزر أو العلاج بالتبريد أو الاستئصال الجراحي.',
    'treat.skinTags.li1': 'الزوائد الجلدية (الأكروكوردونات)',
    'treat.skinTags.li2': 'الشامات الحميدة والوحمات',
    'treat.skinTags.li3': 'التقرنات الدهنية',
    'treat.skinTags.li4': 'الثآليل والأورام الحليمية',
    'treat.skinTags.li5': 'ندبات بسيطة والتهام سريع',
    'treat.prpConc.desc': 'علاج مركز PRP يستخدم عوامل النمو من دمك لتحفيز الشفاء وإنتاج الكولاجين وتجديد الأنسجة.',
    'treat.prpConc.li1': 'تجديد الوجه (فيشل مصاص الدماء)',
    'treat.prpConc.li2': 'تساقط الشعر والترقق',
    'treat.prpConc.li3': 'ندبات حب الشباب والتئام الجروح',
    'treat.prpConc.li4': 'الهالات السوداء تحت العينين والتجاويف',
    'treat.prpConc.li5': 'تحفيز الكولاجين الطبيعي',
    'treat.hairLab.desc': 'التشخيص المختبري الشامل يحدد الأسباب الجذرية لتساقط الشعر، مما يمكن من علاج مستهدف وفعال.',
    'treat.hairLab.li1': 'الثعلبة الأندروجينية (الصلع الوراثي)',
    'treat.hairLab.li2': 'التساقط التفاعلي (تساقط مرتبط بالإجهاد)',
    'treat.hairLab.li3': 'تساقط الشعر بسبب نقص التغذية',
    'treat.hairLab.li4': 'الخلل الهرموني (الغدة الدرقية، DHT)',
    'treat.hairLab.li5': 'خطط علاج مخصصة',
    'treat.exosomalDermapen.desc': 'يجمع إكسوزومال ديرمابين بين الميكرونيدلينغ الطبي والتطبيق الموضعي لمصل غني بالإكسوزومات لتجديد البشرة المتقدم.',
    'treat.exosomalDermapen.li1': 'ندبات حب الشباب والندبات الجراحية',
    'treat.exosomalDermapen.li2': 'التصبغات وأضرار الشمس',
    'treat.exosomalDermapen.li3': 'المسامات المتوسعة وعدم انتظام الملمس',
    'treat.exosomalDermapen.li4': 'الخطوط الدقيقة وترهل الجلد',
    'treat.exosomalDermapen.li5': 'تسريع إصلاح وتجديد البشرة',
    'treat.medicalMeso.desc': 'الميزوثيرابي الطبي هو علاج حقن منظم قائم على وصفة طبية يوفر المكونات النشطة مباشرة للأنسجة المستهدفة.',
    'treat.medicalMeso.li1': 'البشرة شديدة الجفاف',
    'treat.medicalMeso.li2': 'البشرة المتقدمة في السن والمتقدمة ضوئياً',
    'treat.medicalMeso.li3': 'تعافي البشرة بعد الإجراءات',
    'treat.medicalMeso.li4': 'التصبغات والبهتان',
    'treat.medicalMeso.li5': 'إنعاش بقوة الوصفات الطبية',
    'treat.alopecia.desc': 'الثعلبة هي حالة مناعية ذاتية تسبب تساقط الشعر بشكل بقعي. نقدم خيارات علاج متقدمة تشمل العلاج المناعي الموضعي وحقن الكورتيكوستيرويد وعلاج PRP.',
    'treat.alopecia.li1': 'تساقط الشعر البقعي في فروة الرأس',
    'treat.alopecia.li2': 'ثعلبة الحاجبين واللحية',
    'treat.alopecia.li3': 'أشكال الثعلبة الكلية والشاملة',
    'treat.alopecia.li4': 'تساقط الشعر المرتبط بالمناعة الذاتية',
    'treat.alopecia.li5': 'خيارات علاج طبية وتجديدية',
    // Radiant Skin keys
    'radiant.dermapen.desc': 'ميكرونيدلينغ متقدم لتحفيز الكولاجين وتجديد الندبات وتجديد البشرة',
    'radiant.dermapen.1': 'يحفز إنتاج الكولاجين والإيلاستين',
    'radiant.dermapen.2': 'يقلل الخطوط الدقيقة والتجاعيد وندبات حب الشباب',
    'radiant.dermapen.3': 'يحسن ملمس البشرة ولونها',
    'radiant.dermapen.4': 'وقت تعافي ضئيل مع نتائج ملحوظة',
    'radiant.hydracool.desc': 'هيدرا-ديرمابريشن مبرد للتنظيف العميق والترطيب',
    'radiant.hydracool.1': 'طرف مبرد حاصل على براءة اختراع لأقصى راحة',
    'radiant.hydracool.2': 'تنظيف عميق للمسامات واستخراج الشوائب',
    'radiant.hydracool.3': 'ترطيب مكثف',
    'radiant.hydracool.4': 'يقلل الاحمرار والالتهابات',
    'radiant.nanofacial.desc': 'فيشل بالتسريب النانوي لإصلاح البشرة المكثف',
    'radiant.nanofacial.1': 'تقنية التسريب النانوي لاختراق أعمق',
    'radiant.nanofacial.2': 'يصلح حاجز البشرة التالف',
    'radiant.nanofacial.3': 'يضيء ويوحد لون البشرة',
    'radiant.nanofacial.4': 'مناسب لأنواع البشرة الحساسة',
    'radiant.vivace.desc': 'ميكرونيدلينغ بالترددات الراديوية لشد الجلد',
    'radiant.vivace.1': 'يجمع بين الميكرونيدلينغ وطاقة الترددات الراديوية',
    'radiant.vivace.2': 'يشد الجلد المترهل ويقلل التجاعيد',
    'radiant.vivace.3': 'يحفز إنتاج الكولاجين الطبيعي',
    'radiant.vivace.4': 'ألم بسيط مع تعافي أسرع',
    'radiant.hydrafacial.desc': 'تقشير لطيف وفيشل ترطيب عميق',
    'radiant.hydrafacial.1': 'تقشير لطيف يزيل خلايا الجلد الميتة',
    'radiant.hydrafacial.2': 'ترطيب وتغذية عميقة',
    'radiant.hydrafacial.3': 'يحسن نقاء البشرة وإشراقها',
    'radiant.hydrafacial.4': 'بدون توقف، إشراقة فورية',
    'radiant.exosome.desc': 'علاج إكسوزوم تجديدي متقدم لإصلاح البشرة',
    'radiant.exosome.1': 'تواصل خلوي تجديدي متقدم',
    'radiant.exosome.2': 'يسرع إصلاح البشرة والالتئام',
    'radiant.exosome.3': 'يقلل الالتهابات والتصبغات',
    'radiant.exosome.4': 'يعزز الكولاجين لتجديد طويل الأمد',
    'radiant.salmonDna.desc': 'تجديد البشرة بالبولينوكليوتيدات',
    'radiant.salmonDna.1': 'تجديد البشرة بالبولينوكليوتيدات',
    'radiant.salmonDna.2': 'ترطيب عميق وتحسين المرونة',
    'radiant.salmonDna.3': 'يقلل الخطوط الدقيقة والشيخوخة الضوئية',
    'radiant.salmonDna.4': 'مكونات طبيعية متوافقة حيوياً',
    'radiant.carboxy.desc': 'حقن ثاني أكسيد الكربون لأكسجة البشرة وتجديدها',
    'radiant.carboxy.1': 'حقن ثاني أكسيد الكربون الطبية للأكسجة',
    'radiant.carboxy.2': 'يحفز تدفق الدم والكولاجين',
    'radiant.carboxy.3': 'يقلل الهالات السوداء وانتفاخات تحت العين',
    'radiant.carboxy.4': 'يحسن صلابة البشرة ومرونتها',
    'radiant.chemicalPeels.desc': 'تقشير كيميائي احترافي لمشاكل البشرة المختلفة',
    'radiant.chemicalPeels.1': 'محاليل تقشير طبية',
    'radiant.chemicalPeels.2': 'يستهدف حب الشباب والتصبغات والشيخوخة',
    'radiant.chemicalPeels.3': 'قوة وتركيبة قابلة للتخصيص',
    'radiant.chemicalPeels.4': 'يكشف عن بشرة نضرة ومشرقة',
    'radiant.inquire': 'استفسر عبر واتساب',
    'radiant.book': 'احجز الآن',
    'radiant.cta.title': 'لست متأكداً من العلاج المناسب لك؟',
    'radiant.cta.desc': 'احجز استشارة مع أخصائيي الجلدية الخبراء لدينا وسنضع خطة علاج مخصصة تناسب بشرتك.',
    'radiant.cta.book': 'احجز استشارة',
    'radiant.cta.whatsapp': 'تحدث عبر واتساب',
    // Body Contouring keys
    'fatDissolving.desc': 'حقن تقليل الدهون غير الجراحية للمناطق المستهدفة مثل البطن والفخذين وترهلات الخصر والذقن. يكسر هذا العلاج غير الجراحي الخلايا الدهنية طبيعياً.',
    'fatDissolving.l1': 'تقليل الدهون المستهدف',
    'fatDissolving.l2': 'طفيف التوغل بدون توقف',
    'fatDissolving.l3': 'نتائج تدريجية طبيعية المظهر',
    'fatDissolving.l4': 'مناسب للذقن والبطن والفخذين وترهلات الخصر',
    'btlExilis.desc': 'علاج غير جراحي متطور بالترددات الراديوية والموجات فوق الصوتية لشد الجلد وتقليل الدهون ونحت الجسم.',
    'btlExilis.l1': 'ترددات راديوية غير جراحية + موجات فوق صوتية',
    'btlExilis.l2': 'شد الجلد وتقليل الدهون في جلسة واحدة',
    'btlExilis.l3': 'آمن ومريح بدون توقف',
    'btlExilis.l4': 'مثالي للبطن والذراعين والفخذين والأرداف',
    'collagenStim.desc': 'علاجات محفزة حيوياً تعزز إنتاج الكولاجين الطبيعي لتحسين صلابة البشرة ومرونتها وتحديد الجسم.',
    'collagenStim.l1': 'تحفيز الكولاجين الطبيعي',
    'collagenStim.l2': 'يحسن صلابة البشرة ومرونتها',
    'collagenStim.l3': 'نتائج تدريجية طويلة الأمد',
    'collagenStim.l4': 'فعال للأرداف والذراعين والبطن والفخذين',
    'doubleChin.desc': 'تقليل الذقن المزدوجة غير الجراحي باستخدام حقن متقدمة تكسر الخلايا الدهنية تحت الذقن.',
    'doubleChin.l1': 'تقليل الدهون تحت الذقن غير الجراحي',
    'doubleChin.l2': 'إجراء سريع مع انزعاج بسيط',
    'doubleChin.l3': 'نتائج ملحوظة في غضون أسابيع',
    'doubleChin.l4': 'يعزز تحديد خط الفك',
    // Laser Hair Removal keys
    'laserHair.desc': 'نظام إزالة الشعر بالليزر المتقدم لدينا يوفر تقليل شعر دائم وآمن وفعال للرجال والنساء من جميع أنواع البشرة.',
    'laserHair.l1': 'تقليل شعر دائم آمن وفعال',
    'laserHair.l2': 'مناسب لجميع أنواع البشرة بما فيها البشرة الداكنة',
    'laserHair.l3': 'تقنية تبريد متقدمة لعلاج خالٍ من الألم',
    'laserHair.l4': 'يعالج الوجه وتحت الإبطين والذراعين والساقين والبيكيني والصدر والظهر والجسم كامل',
    'laserHair.l5': 'خطط علاج مخصصة لنتائج مثالية',
    'laserRejuv.desc': 'علاج ليزر غير استئصالي يحفز إنتاج الكولاجين ويعيد سطح البشرة لتقليل الخطوط الدقيقة والتجاعيد وأضرار الشمس.',
    'laserRejuv.l1': 'يحفز إنتاج الكولاجين الطبيعي',
    'laserRejuv.l2': 'يقلل الخطوط الدقيقة والتجاعيد وأضرار الشمس',
    'laserRejuv.l3': 'يحسن ملمس البشرة وإشراقها',
    'laserRejuv.l4': 'وقت تعافي ضئيل، نتائج طبيعية تدريجية',
    'pigmentation.desc': 'علاجات متقدمة بالليزر والضوء تستهدف الميلانين الزائد لتصحيح فرط التصبغ والكلف والبقع الشمسية.',
    'pigmentation.l1': 'يستهدف الكلف والبقع الشمسية وبقع العمر',
    'pigmentation.l2': 'يصحح فرط التصبغ التالي للالتهاب',
    'pigmentation.l3': 'مخصص لجميع درجات البشرة',
    'pigmentation.l4': 'نتائج لون بشرة موحد ومشرق',
    'tightening.desc': 'علاجات شد الجلد غير الجراحية بالليزر والترددات الراديوية تحفز إنتاج الكولاجين والإيلاستين لشد الجلد المترهل.',
    'tightening.l1': 'شد ورفع الجلد غير الجراحي',
    'tightening.l2': 'يحفز إنتاج الكولاجين والإيلاستين',
    'tightening.l3': 'فعال للوجه والرقبة والبطن والذراعين والفخذين',
    'tightening.l4': 'بدون توقف، رفع طبيعي المظهر',
    'treat.laserRejuv': 'تجديد البشرة بالليزر',
    'treat.pigmentation': 'تصحيح التصبغات',
    'treat.skinTightening': 'شد الجلد',
  };

  function switchLang(lang) {
    currentLang = lang;
    const dict = lang === 'ar' ? arText : enText;

    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key = el.dataset.i18n;
      if (dict[key]) {
        if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') el.placeholder = dict[key];
        else if (el.tagName === 'OPTION') el.textContent = dict[key];
        else if (el.tagName === 'SELECT') {
          const ph = el.querySelector('option[value=""]');
          if (ph) ph.textContent = dict[key];
        } else el.innerHTML = dict[key];
      }
    });

    document.body.classList.toggle('rtl', lang === 'ar');
    document.documentElement.lang = lang === 'ar' ? 'ar' : 'en';
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    const toggle = document.getElementById('langToggle');
    if (toggle) toggle.textContent = lang === 'ar' ? 'English' : 'العربية';

    document.querySelectorAll('.ar-text').forEach(el => { el.style.display = lang === 'ar' ? 'inline' : 'none'; });
  }

  const langToggle = document.getElementById('langToggle');
  if (langToggle) {
    langToggle.addEventListener('click', () => switchLang(currentLang === 'en' ? 'ar' : 'en'));
  }

  // Contact form
  const contactForm = document.getElementById('contactForm');
  const formStatus = document.getElementById('formStatus');

  if (contactForm) {
    contactForm.addEventListener('submit', async (e) => {
      e.preventDefault();
      const submitBtn = document.getElementById('formSubmit');
      submitBtn.disabled = true;
      submitBtn.innerHTML = '<span>Sending...</span> <i class="fas fa-spinner fa-spin"></i>';

      const payload = {
        name: document.getElementById('formName').value.trim(),
        phone: document.getElementById('formPhone').value.trim(),
        email: document.getElementById('formEmail').value.trim(),
        service: document.getElementById('formService').value,
        message: document.getElementById('formMessage').value.trim()
      };

      try {
        const res = await fetch('/api/contact', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(payload)
        });
        const result = await res.json();
        if (!result.success) throw new Error(result.message);

        formStatus.className = 'form-status success';
        formStatus.textContent = currentLang === 'ar'
          ? 'شكراً لتواصلك معنا! سنعود إليك قريباً.'
          : 'Thank you! We\'ll get back to you shortly.';
        formStatus.style.display = 'block';
        contactForm.reset();
      } catch (err) {
        console.error('Form error:', err);
        formStatus.className = 'form-status error';
        formStatus.textContent = currentLang === 'ar'
          ? 'حدث خطأ. يرجى المحاولة مرة أخرى أو الاتصال بنا عبر واتساب.'
          : 'Something went wrong. Please try again or contact us via WhatsApp.';
        formStatus.style.display = 'block';
      }

      submitBtn.disabled = false;
      submitBtn.innerHTML = '<span>Send Message</span> <i class="fas fa-paper-plane"></i>';
    });
  }

  // Add fadeIn keyframe
  const style = document.createElement('style');
  style.textContent = `@keyframes fadeIn { from { opacity: 0; transform: translateY(20px); } to { opacity: 1; transform: translateY(0); } }`;
  document.head.appendChild(style);

});
